name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Generate API Docs 🔧
        run: |
          git clone --depth 1 https://github.com/frappe/frappe /opt/frappe
          python -m venv env
          . ./env/bin/activate
          pip install -e /opt/frappe
          pip install -e .
          pip install pdoc
          pdoc -o build castlecraft

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: build
